!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers:
- mHandle: 400
  mName: Pigeon X
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonAccelWrapper
- mHandle: 401
  mName: Pigeon Y
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonAccelWrapper
- mHandle: 402
  mName: Pigeon Z
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonAccelWrapper
mAnalogIn: []
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers: {}
mDigitalIO: []
mEncoders:
- mConnectedSpeedControllerHandle: 101
  mHandle: 101
  mName: CAN Encoder (1)
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
- mConnectedSpeedControllerHandle: 103
  mHandle: 103
  mName: CAN Encoder (3)
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
- mConnectedSpeedControllerHandle: 105
  mHandle: 105
  mName: CAN Encoder (5)
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
- mConnectedSpeedControllerHandle: 106
  mHandle: 106
  mName: CAN Encoder (6)
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
mGyros:
- mHandle: 400
  mName: Pigeon Yaw
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonGyroWrapper
- mHandle: 401
  mName: Pigeon Pitch
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonGyroWrapper
- mHandle: 402
  mName: Pigeon Roll
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonGyroWrapper
mPwm:
- mHandle: 101
  mMotorModelConfig:
    mGearReduction: 10.0
    mGearboxEfficiency: 0.8
    mHasBrake: false
    mInverted: false
    mMotorType: CIM
    mNumMotors: 2
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 3.14
    mLoad: 0.25
  mName: Left Drive (M)
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 102
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Rev SC 2
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 103
  mMotorModelConfig:
    mGearReduction: 10.0
    mGearboxEfficiency: 0.8
    mHasBrake: false
    mInverted: true
    mMotorType: CIM
    mNumMotors: 2
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 3.14
    mLoad: 0.25
  mName: RIght Drive (M)
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 104
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Rev SC 4
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 105
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Rev SC 5
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 106
  mMotorModelConfig:
    mGearReduction: 5.0
    mGearboxEfficiency: 0.8
    mHasBrake: false
    mInverted: false
    mMotorType: CIM
    mNumMotors: 2
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 6.28
    mLoad: 0.25
  mName: Shooter
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
mRelays: []
mSimulatorComponents:
- !!com.snobot.simulator.simulator_components.config.TankDriveConfig
  mGyroHandle: 400
  mLeftMotorHandle: 101
  mRightMotorHandle: 103
  mTurnKp: 33.33
mSolenoids: []
